config/routes.rb
BlogDemo::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :entries, except: :index
  resources :comments
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',      via: 'delete' 
  match '/following-entries', to: 'users#following_entries', via: 'get'

end

app/views/shared/_check_length.html.erb
<div class="row">
	<div class="span4 offset4 pull-right">
		<h2 id="character-left"><%= @length %> character lefts</h2>
	</div>
</div>

app/views/shared/_comment.html.erb
<li id="<%= comment.id %>">
    <%= link_to gravatar_for(comment.user), comment.user %>
    <span class="user">
      <%= link_to comment.user.name, comment.user %>
    </span>
  <section>
    <%= wrap(comment.content) %>
    <br>
    <span class="timestamp">Posted <%= time_ago_in_words(comment.created_at) %> ago at <%= comment.created_at.strftime('%Y-%m-%d') %></span>
    <%= render "shared/delete_link", object: comment %>
  </section>  
</li>

app/views/shared/_comment_form.html.erb
<%= form_for(current_user.comments.build(entry: @entry), remote: true) do |f| %>	
	<div><%= f.hidden_field :entry_id %></div>
	<div class="row">
		<div class="span1"><%= link_to gravatar_for(current_user), current_user %></div>
		<div class="span4"><%= f.text_area :content, placeholder: "200 characters allowed", "data-maximum" => "200" %></div>
	</div>
	<%= render partial: 'shared/check_length', locals: { :@length => 200} %>
	<%= f.submit "comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/_delete_ajax.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_delete_link.html.erb
<% if current_user?(object.user) %>
    <%= link_to "delete", object, method: :delete,
                                     data: { confirm: "You sure?" },
                                     remote: true
                                     %>
<% end %>

app/views/shared/_entries.html.erb
<% if @entries.any? %>
  <ol class="entries">
    <%= render partial: 'shared/entry', collection: @entries %>
  </ol>
  <%= will_paginate @entries %>
<% end %>

app/views/shared/_entry.html.erb
<li id="<%= entry.id %>">
  <%= link_to gravatar_for(entry.user), entry.user, alt: entry.user.name %>
    <span class="user">
      <%= link_to entry.title, entry %>
    </span>
    <span class="content"><%= wrap(entry.body.slice(0,300)<<'...') %></span>
    <br/>
    <span class="timestamp">
      Posted <%= time_ago_in_words(entry.created_at) %> ago at <%= entry.created_at.strftime('%Y-%m-%d') %>
    </span>
  
  <%= render "shared/delete_link", object: entry %>
  <% if current_user?(entry.user)  %>
  | <%= link_to " edit", edit_entry_path(entry) %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow_link.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <h2><%= f.submit "Follow #{@user.name} to comment!", class: "btn" %></h2>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
</span>